"""empty message

Revision ID: 914c2c17810f
Revises: 
Create Date: 2024-06-25 13:28:54.780652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914c2c17810f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active_workout_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workout_routines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sunday', sa.Text(), nullable=False),
    sa.Column('monday', sa.Text(), nullable=False),
    sa.Column('tuesday', sa.Text(), nullable=False),
    sa.Column('wednesday', sa.Text(), nullable=False),
    sa.Column('thursday', sa.Text(), nullable=False),
    sa.Column('friday', sa.Text(), nullable=False),
    sa.Column('saturday', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_metrics_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_workout_routine',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_routine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_workout_routine_user_id_users')),
    sa.ForeignKeyConstraint(['workout_routine_id'], ['workout_routines.id'], name=op.f('fk_user_workout_routine_workout_routine_id_workout_routines')),
    sa.PrimaryKeyConstraint('user_id', 'workout_routine_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_workout_routine')
    op.drop_table('user_metrics')
    op.drop_table('exercise_logs')
    op.drop_table('workout_routines')
    op.drop_table('users')
    # ### end Alembic commands ###
